### ISSUE TITLE
CASA6/python3: replace raw_input() with input() in scriptForImagingPrep_template.py

### ISSUE THREAD

**Issue by privong** [aakepley/ALMAImagingScript#4]
`raw_input()` was removed in python3. The functionality was replaced with `input()`. The two instances of `raw_input()` need to be replaced with `input()` in order to run `scriptForImagingPrep_template.py` in CASA 6.

**Comment by aakepley** [comment]
Resolved by commit 5962c7343af482b5469c225ed99fdfcf791cf5d3
